spring:
  application:
    name: api-gateway-ms
  config:
    import: optional:configserver:http://localhost:8888
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    gateway:
      routes:
        ### users-ms
        - id: users-status-check
          uri: lb://users-ms
          predicates:
            - Path=/users-ms/api/v1/clients/status/check
            - Method=GET
            - Header=Authorization, Bearer (.*)
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/users-ms/(?<segment>.*), /${segment}
            - AuthorizationHeaderFilter

        - id: users-ms-create-user
          uri: lb://users-ms
          predicates:
            - Path=/users-ms/api/v1/users/create
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/users-ms/(?<segment>.*), /${segment}

        - id: users-ms-login
          uri: lb://users-ms
          predicates:
            - Path=/users-ms/api/v1/users/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/users-ms/(?<segment>.*), /${segment}

        - id: users-ms-get-update-delete
          uri: lb://users-ms
          predicates:
            - Path=/users-ms/api/v1/users/**
            - Method=GET,PUT,DELETE
            - Header=Authorization, Bearer (.*)
          filters:
            - RemoveRequestHeader=Cookie
            - AuthorizationHeaderFilter
            - RewritePath=/users-ms/(?<segment>.*), /${segment}

        - id: users-ms-h2-console
          uri: lb://users-ms
          predicates:
            - Path=/users-ms/api/v1/h2-console
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/users-ms/(?<segment>.*), /${segment}

        - id: users-ms-actuator
          uri: lb://users-ms
          predicates:
            - Path=/users-ms/api/v1/actuator/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/users-ms/(?<segment>.*), /${segment}

        - id: client-account-ms
          uri: lb://client-account-ms
          predicates:
            - Path=/client-account-ms/api/v1//clients/**
            - Method=GET,POST,PUT,PATCH,DELETE
            - Header=Authorization, Bearer (.*)
          filters:
            - RemoveRequestHeader=Cookie
            - AuthorizationHeaderFilter
            - RewritePath=/client-account-ms/(?<segment>.*), /${segment}

        ### client-account-ms
        - id: client-account-ms-create-account
          uri: lb://client-account-ms
          predicates:
            - Path=/client-account-ms/api/v1/account
            - Method=POST
            - Header=Authorization, Bearer (.*)
          filters:
            - RemoveRequestHeader=Cookie
            - AuthorizationHeaderFilter
            - RewritePath=/transaction-ms/(?<segment>.*), /${segment}

        - id: client-account-ms-get-account
          uri: lb://client-account-ms
          predicates:
            - Path=/client-account-ms/api/v1/account/**
            - Method=GET
            - Header=Authorization, Bearer (.*)
          filters:
            - RemoveRequestHeader=Cookie
            - AuthorizationHeaderFilter
            - RewritePath=/transaction-ms/(?<segment>.*), /${segment}

        - id: client-account-ms-get-client-accounts
          uri: lb://client-account-ms
          predicates:
            - Path=/client-account-ms/api/v1/account/list/**
            - Method=GET
            - Header=Authorization, Bearer (.*)
          filters:
            - RemoveRequestHeader=Cookie
            - AuthorizationHeaderFilter
            - RewritePath=/transaction-ms/(?<segment>.*), /${segment}

        - id: client-account-ms-update-account
          uri: lb://client-account-ms
          predicates:
            - Path=/client-account-ms/api/v1/account
            - Method=POST
            - Header=Authorization, Bearer (.*)
          filters:
            - RemoveRequestHeader=Cookie
            - AuthorizationHeaderFilter
            - RewritePath=/transaction-ms/(?<segment>.*), /${segment}

        - id: client-account-ms-delete-account
          uri: lb://client-account-ms
          predicates:
            - Path=/client-account-ms/api/v1/account/**
            - Method=DELETE
            - Header=Authorization, Bearer (.*)
          filters:
            - RemoveRequestHeader=Cookie
            - AuthorizationHeaderFilter
            - RewritePath=/transaction-ms/(?<segment>.*), /${segment}

        ### transaction-ms
        - id: transaction-ms-create-transaction
          uri: lb://transaction-ms
          predicates:
            - Path=/transaction-ms/api/v1/transaction
            - Method=POST
            - Header=Authorization, Bearer (.*)
          filters:
            - RemoveRequestHeader=Cookie
            - AuthorizationHeaderFilter
            - RewritePath=/transaction-ms/api/v1/transaction, /api/v1/transaction

        - id: transaction-ms-get-transaction
          uri: lb://transaction-ms
          predicates:
            - Path=/transaction-ms/api/v1/transaction/**
            - Method=GET
            - Header=Authorization, Bearer (.*)
          filters:
            - RemoveRequestHeader=Cookie
            - AuthorizationHeaderFilter
            - RewritePath=/transaction-ms/(?<segment>.*), /${segment}

        - id: transaction-ms-cansel
          uri: lb://transaction-ms
          predicates:
            - Path=/transaction-ms/api/v1/transaction/cansel/**
            - Method=GET
            - Header=Authorization, Bearer (.*)
          filters:
            - RemoveRequestHeader=Cookie
            - AuthorizationHeaderFilter
            - RewritePath=/transaction-ms/(?<segment>.*), /${segment}


server:
  port: ${PORT:8082}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    preferIpAddress: true

token:
  secret: dgjorufhrsnjdu438fkdj38fdmcv7dm3ckvhrsnjjuwelueivhe848fhedldh5ndk

management:
  endpoint:
    gateway:
      access: unrestricted
  endpoints:
    web:
      exposure:
        include: gateway,health,mappings